name: Checkov Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  checkov:
    runs-on: ubuntu-latest
    name: Checkov Terraform Security Scan

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          framework: terraform
          soft_fail: true
          skip_check: CKV_AWS_117,CKV_AWS_272,CKV_AWS_144,CKV2_AWS_61,CKV2_AWS_62,CKV_AWS_115,CKV_AWS_338,CKV2_AWS_29,CKV_AWS_158,CKV_AWS_50,CKV_AWS_94,CKV_AWS_309,CKV2_AWS_57,CKV2_AWS_3,CKV2_AWS_48
# CKV_AWS_117 - Lambda VPC: No VPC within the architecture. All services communicate via TLS encrypted AWS managed endpoints.
# CKV_AWS_272 - Lambda Code Signing: Code Signing is not required for this project.
# CKV_AWS_144 - S3 cross-region replication: Cross-region replication creates unnecessary cost for data that can be regenerated by running the scan.
# CKV2_AWS_61 - S3 lifecycle policy: Lifecycle policies are configured on all buckets. Look in s3.tf for more information.
# CKV2_AWS_62 - S3 event notifications: Lambda is triggered via the API Gateway and Step Fuctions. Not needed for this project.
# CKV_AWS_115 - Lambda reserved concurrency: Not supported on account tier.
# CKV_AWS_338 - CloudWatch log group retention: CloudWatch logs are configured for 365 days retention. See monitoring.tf for more details.
# CKV2_AWS_29 - API Gateway WAF: WAF is deployed in terraform and associated manually via console. Terraform does not offer support for HTTP API v2 stage ARN format.
# CKV_AWS_158 - CloudWatch log group KMS encryption: KMS encryption is configured on all CloudWatch log groups.
# CKV_AWS_50 - Lambda X-Ray tracing: X-Ray tracing is enabled on all lambda functions. See lambda.tf for more details.
# CKV_AWS_309 - API Gateway route authorization: Route-level authorization is not implemented for this project. WAf rate limiting and API key header validation provide access control.
# CKV2_AWS_57 - Secrets Manager rotation: Secrets contains static third-party API key from HaveIBeenPwned. Automatic rotation would invalidate the API key.
# CKV2_AWS_3 - GuardDuty org/region: Single account deployment. Configuration isn't necessary.
# CKV2_AWS_48 - Config has been set to record all resources. See security.tf for more details.
